# Generated by Django 2.0.7 on 2020-01-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooteravailability',
            name='scooter_name',
            field=models.TextField(default='Abc'),
        ),
    ]
