# Generated by Django 2.1.5 on 2020-01-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0002_scooteravailability_scooter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scooteravailability',
            name='scooter_name',
        ),
    ]
