# Generated by Django 2.1.5 on 2020-01-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0003_remove_scooteravailability_scooter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScooterBooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ScooterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scooter_numplate', models.CharField(max_length=10)),
                ('scooter_color', models.CharField(max_length=10)),
                ('scooter_company', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='scooteravailability',
            name='scooter_status',
        ),
        migrations.AddField(
            model_name='scooterbooked',
            name='scooter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooters.ScooterDetails'),
        ),
        migrations.AddField(
            model_name='scooteravailability',
            name='scooter_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scooters.ScooterDetails'),
            preserve_default=False,
        ),
    ]
