# Generated by Django 2.1.5 on 2020-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0004_auto_20200119_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooterbooked',
            name='scooter_id',
            field=models.IntegerField(),
        ),
    ]
