# Generated by Django 2.1.5 on 2020-01-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0005_auto_20200119_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScooterBooked',
        ),
        migrations.AddField(
            model_name='scooteravailability',
            name='scooter_status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('inservice', 'In-service')], default='available', max_length=10),
        ),
    ]
