# Generated by Django 2.1.5 on 2020-01-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0006_auto_20200121_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scooteravailability',
            name='scooter_id',
        ),
        migrations.DeleteModel(
            name='ScooterDetails',
        ),
    ]
