# Generated by Django 2.1.5 on 2020-01-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0007_auto_20200121_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScooterLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('rent', models.FloatField(null=True)),
                ('scooter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooters.ScooterAvailability')),
            ],
        ),
    ]
